CREATE DATABASE AdvancedSearchEngine

USE AdvancedSearchEngine

CREATE TABLE SearchHistory
(
	SearchHistoryID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SearchInput NVARCHAR(255) NOT NULL,
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL 
)

CREATE TABLE Category
(
	CategoryID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,	
	CategoryName NVARCHAR(255) NOT NULL,
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL 
)

CREATE TABLE SubCategory
(
	SubCategoryID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,	
	SubCategoryName NVARCHAR(255) NOT NULL,
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL,
	CategoryID INT FOREIGN KEY REFERENCES Category(CategoryID) NOT NULL
)

CREATE TABLE ProductImage    --ovo je naslovna slika
(
	ProductImageID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,	
	ImageBase64 NVARCHAR(255) NULL,
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL 
)

CREATE TABLE ProductColor
(
	ProductColorID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ColorName NVARCHAR(255) NOT NULL,	
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL,
)

CREATE TABLE ProductBrand
(
	ProductBrandID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	BrandName NVARCHAR(255) NOT NULL,	
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL,
)

CREATE TABLE ProductDepartment
(
	ProductDepartmentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DepartmentName NVARCHAR(255) NOT NULL,	
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL,
)

CREATE TABLE Size
(
	SizeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SizeName NVARCHAR(255) NOT NULL,	
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL,
)

CREATE TABLE Product
(
	ProductID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ProductName NVARCHAR(255) NOT NULL,
	ProductCaption NVARCHAR(255) NOT NULL,
	ProductPrice DECIMAL(8,2) NOT NULL,
	DateCreated DATETIME DEFAULT GETDATE() NOT NULL,
	SubCategoryID INT FOREIGN KEY REFERENCES SubCategory(SubCategoryID) NOT NULL,
	ProductImageID INT FOREIGN KEY REFERENCES ProductImage(ProductImageID) NOT NULL,
    ProductColorID INT FOREIGN KEY REFERENCES ProductColor(ProductColorID) NOT NULL,
	ProductBrandID INT FOREIGN KEY REFERENCES ProductBrand(ProductBrandID) NOT NULL,
	ProductDepartmentID INT FOREIGN KEY REFERENCES ProductDepartment(ProductDepartmentID) NOT NULL,
)

CREATE TABLE ProductSize
(   ProductSizeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ProductID INT FOREIGN KEY REFERENCES Product(ProductID) NOT NULL,
	SizeID INT FOREIGN KEY REFERENCES Size(SizeID) NOT NULL,
	Available BIT NOT NULL DEFAULT 1
)

CREATE TABLE Users
(
	UserID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Surname NVARCHAR(100) NOT NULL,
	Username NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL
)

ALTER TABLE SearchHistory
ADD UserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL
